name: Dev-Build
on:
  workflow_run:
    workflows: ['Release-Tag']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release Tag
        if: success()
        run: |
          VERSION=$(node -pe "require('./package.json').version")
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: 'CHANGELOG.md'
        env:
          tag: $VERSION
